<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_MessageQueue
 */
?>
<?php
if ($block->checkCustomAttribute()) {
    ?>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= /* @noEscape */ __('Target Information') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <?= $block->getChildHtml(); ?>
            <tr>
                <th><?= /* @noEscape */ __('Target Customer ID:') ?></th>
                <td><?= /* @noEscape */ $block->getCustomAttribute(); ?></td> 
            </tr>
            <?php if ($block->getComponent() == 'GP' || $block->getComponent() == 'AX'
                    || $block->getComponent() == 'NAV'
                    || $block->getComponent() == 'BC') { ?>
                <tr>
                    <th><?= /* @noEscape */ __('Price Level:') ?></th>
                        <?php $priceLevel = $block->getCustomerPricelevel();
                        if ($priceLevel == '') {
                            ?>
                        <td><?= /* @noEscape */ __('Not Available'); ?></td> 
                            <?php
                        } else {
                            ?>
                        <td><?= /* @noEscape */ $priceLevel; ?></td> 
                            <?php
                        }
                        ?>
                </tr>
<?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>
