<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Theme\Block\Html\Header\Logo $block $storeName */
?>
<th width="200">
    <div>
        <a href="<?= $block->escapeUrl($block->getUrl('')) ?>"
           title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>">
            <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
                 title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
                 alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            />
        </a>
    </div>
</th>
<br />
