<?php
// @codingStandardsIgnoreFile
/** @var \Vueai\ProductRecommendations\Block\Adminhtml\Index\Signup $block */
?>

<form class="productrecommendations recommendation-block" action="<?= $block->escapeUrl($block->getFormAction()) ?>" method="POST" enctype="multipart/form-data" id ="productrecommendations">

    <div class="form-logo">
    <img src='<?php echo $block->escapeUrl($block->getMediaUrl()); ?>' alt="Logo">
    </div>
    <div class="form-stepsblock">
        <p>
            <?php echo $block->escapeHtml(__('You are signing up for')); ?> <a href="https://vue.ai/" target="_blank">Vue.ai</a>
            <?php echo $block->escapeHtml(__("which will enable you to individualize your shopper's experience by setting up the following recommendations on your website: "))?>
        </p>
        <div class="form-infoblock">
        <p><?php echo $block->escapeHtml(__("1. Styling Recommendations")); ?></p>
        <p><?php echo $block->escapeHtml(__("2. Inspired by Browsing History")); ?></p>
        <p><?php echo $block->escapeHtml(__("3. Trending Products")); ?></p>
        <p><?php echo $block->escapeHtml(__("4. Visually Similar Recommendations")); ?></p>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field required">
            <div class="control">
                <input type="text" id="username"
                       name="name" placeholder="<?php echo $block->escapeHtml(__('Name')) ?>"
                       class="input-text"
                       value="<?php echo $block->getCurrentAdminName(); ?>"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <div class="control">
                <input type="text" id="email"
                       name="email" placeholder="<?php echo $block->escapeHtml(__('Email')) ?>"
                       class="input-text"
                       value="<?php echo $block->getCurrentAdminEmail(); ?>"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <div class="control">
                <input type="text" id="company"
                       name="company" placeholder="<?php echo $block->escapeHtml(__('Company')) ?>" class="input-text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <div class="control">
                <input type="text" id="phone" placeholder="<?php echo $block->escapeHtml(__('Phone Number')) ?>"
                       name="phone"
                       class="input-text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <div class="control" name="region" data-validate="{required:true}">
                <select name="region" data-validate="{required:true}">
                    <option>Select region </option>
                    <option value="americas">Americas</option>
                    <option value="europe">Europe</option>
                    <option value="middle-east-asia-pacific">Middle East, Asia Pacific</option>
                </select>
            </div>
        </div>
        <div class="field required">
            <div class="store">
                <input type="hidden" id="store" placeholder="<?php echo $block->escapeHtml(__('store')) ?>"
                       name="store"
                       class="input-text"
                value="<?php echo $block->getStoreId(); ?>">
            </div>
        </div>
        <div class="field required choice">
            <div class="store">
                <input type="checkbox" data-validate="{required:true}" name="custom-terms" title="<?php echo $block->escapeHtml(__('I agree to the Tearms & Conditions and Privacy Policy')) ?>" id="register-input-custom" class="checkbox">
                <label for="custom-terms" class="label"><span><?php echo $block->escapeHtml(__('I agree to the ')) ?><a href="https://vue.ai/privacy-policy.html" target="_blank"><?php echo $block->escapeHtml(__('Tearms & Conditions')) ?></a> <?php echo $block->escapeHtml(__('and')) ?> <a href="https://vue.ai/privacy-policy.html" target="_blank"><?php echo $block->escapeHtml(__('Privacy Policy')) ?></a></span> </label>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php echo $block->escapeHtml(__('Submit')) ?>">
                <span><?php echo $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
    <?php echo $block->getBlockHtml('formkey')?>
</form>

<script type="text/x-magento-init">
    {
        "#productrecommendations": {
            "validation": {}
        }
    }
</script>