<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_brand')): ?>
        <?php if ($block->getConfig('product_page_settings/show_brand_img')): ?>
			<?php $brand = $block->getBrand() ?>
            <?php if($brand): ?>
				<div class="product-brand">
					<div class="brand-name">
						<strong class="type"><?php echo __('Brand'); ?></strong>
						<a title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>"><?php echo $block->getBrand()->getName(); ?></a>
					</div>
					<div class="block product-brand">
					<?php $img = $brand->getImageUrl(); ?>
					<?php if ($img) { ?>
						<div class="brand-image">
							<a title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>"><img class="image img-responsive" style="max-height: 90px;" src="<?php echo $img; ?>" alt="<?php echo $brand->getName(); ?>"/></a>
						</div>
					<?php } ?>
				</div>
				</div>
			<?php endif ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
