<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_NetTerms
 * @codingStandardsIgnoreFile
 */
/**
 * @var $block Purchaseorder
 */

use Magento\OfflinePayments\Block\Info\Purchaseorder;

?>
<dl class="payment-method purchase order">
    <dt class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></dt>
</dl>

