<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_BillPay
 * @codingStandardsIgnoreFile
 */
?>

<?php $_payments = $block->getPayment(); ?>
<?php if ($_payments && !empty($_payments)): ?>
    <div class="block block-payment-info">
        <div class="block-title">
            <b>TRANSACTION DETAILS</b>
        </div>
        <div class="box-content">
            <label>Transaction ID</label> : <?php echo $block->escapeHtml($_payments['payment_trans_id']); ?><br>
            <label>Status</label> : <?php echo $block->escapeHtml($_payments['status']); ?><br>
            <label>Comments</label> : <?php echo $block->escapeHtml($_payments['payment_comment']); ?><br>
        </div>
    </div>
<?php endif; ?>
