<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
/** @var $viewModel \Bss\CustomerAttributes\ViewModel\Address\CustomAddressHelper */
// @codingStandardsIgnoreFile
?>
<?php $viewModel = $block->getViewModel(); ?>
<?php $attributeHelper = $viewModel->getAttributeHelper();?>

<div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Manage Addresses')) ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
                <?php if ($attributeHelper->isEnable() && $viewModel->getBillingAddressAttribute()!== null): ?>
                    <?php  foreach ($attributeHelper->getAddressCollection() as $customAddress): ?>
                        <?php
                        $fieldValue = '';
                        $customAttributeCode = $customAddress->getAttributeCode();
                        if ($viewModel->getBillingAddressAttribute()->getCustomAttribute($customAttributeCode)!==null) {
                            $fieldValue = $viewModel->getBillingAddressAttribute()->getCustomAttribute($customAttributeCode)->getValue();
                        } elseif ($customAddress->getDefaultValue()) {
                            $fieldValue = $customAddress->getDefaultValue();
                        }
                        $optionValue =  $viewModel->getAttributeHelper()->getValueAddressAttributeOption($customAttributeCode, $fieldValue);
                        if ($optionValue) {
                            $fieldValue = $optionValue === 'file' ? $attributeHelper->getFileName($fieldValue) : $optionValue;
                        }
                        if ($customAddress->getFrontendInput() == 'date'){
                            $fieldValue = $attributeHelper->formatDateTime($fieldValue);
                        }
                        ?>
                        <?php if ($attributeHelper->isAddressShowInBook($customAddress->getAttributeCode()) &&
                            $fieldValue!=='' && $attributeHelper->isVisible($customAddress->getAttributeCode())):?>
                            <div class="field custom_attribute">
                                <label class="label"><span><?= $customAddress->getStoreLabel($attributeHelper->getStoreId()) . ': ' . $fieldValue ?></label>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
                <?php if ($attributeHelper->isEnable() && $viewModel->getShippingAddressAttribute()!== null): ?>
                    <?php  foreach ($attributeHelper->getAddressCollection() as $customAddress): ?>
                        <?php
                        $fieldValue = '';
                        $customAttributeCode = $customAddress->getAttributeCode();
                        if ($viewModel->getShippingAddressAttribute()->getCustomAttribute($customAttributeCode)!==null) {
                            $fieldValue = $viewModel->getShippingAddressAttribute()->getCustomAttribute($customAttributeCode)->getValue();
                        } elseif ($customAddress->getDefaultValue()) {
                            $fieldValue = $customAddress->getDefaultValue();
                        }
                        $optionValue =  $viewModel->getAttributeHelper()->getValueAddressAttributeOption($customAttributeCode, $fieldValue);
                        if ($optionValue) {
                            $fieldValue = $optionValue === 'file' ? $attributeHelper->getFileName($fieldValue) : $optionValue;
                        }
                        if ($customAddress->getFrontendInput() == 'date'){
                            $fieldValue = $attributeHelper->formatDateTime($fieldValue);
                        }
                        ?>
                        <?php if ($attributeHelper->isAddressShowInBook($customAddress->getAttributeCode()) &&
                            $fieldValue!=='' && $attributeHelper->isVisible($customAddress->getAttributeCode())):?>
                            <div class="field custom_attribute">
                                <label class="label"><span><?= $customAddress->getStoreLabel($attributeHelper->getStoreId()) . ': ' . $fieldValue ?></label>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
    </div>
</div>
