<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Ca\Block\Form */
?>
<div data-role="aw-ca-form" data-bind="scope: 'awCaForm'" class="aw-ca__form">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-ca-form]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
