<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/**
 * @var \Bss\CustomerAttributes\Block\Adminhtml\Order\Address\Form $block
 */
?>

<?php $customAddress = $block->getCustomAddressValues(); ?>
<?php if ($customAddress): ?>
	<script type="text/x-magento-init">
	    {
	        "*": {
	            "Bss_CustomerAttributes/js/order/address/customer-address": {
	               "customAddress": <?= /* @escapeNotVerified */ $customAddress ?>
	            }
	        }
	    }
	</script>
<?php endif; ?>

<script type="text/x-magento-init">
	    {
	        "*": {
	            "Bss_CustomerAttributes/js/order/address/customer-address-file": {}
	        }
	    }
</script>
