<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\QuickOrder\Block\Product\Renderer\Swatches\Configurable */
?>
<div class="swatch-opt" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Aheadworks_QuickOrder/js/widget/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Aheadworks_QuickOrder/js/widget/swatch-values-setter": {
                "values": <?php /* @noEscape */ echo $block->getSelectedSwatchesJson(); ?>
            }
        }
    }
</script>
