<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_B2bRegistration
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Authorization Link block template
 *
 * @var Bss\B2bRegistration\Block\Account\AuthorizationLink $block
 */
?>
<?php 
	$dataPostParam = '';
	$enableShortCut = $block->isEnableShortcutLink();
	$shortCutLinkText = $block->getShortcutLinkText();
	$b2bCreateUrl = $block->getUrlB2bAccountCreate();
	$enable = $block->isEnable();
?>
<?php if ($block->checkForceLoginInstall()) : ?>
	<?php
	$enableForceLogin = $block->isEnableRegister();
	$enableRegister = $block->getEnableRegister();
	if ($block->isLoggedIn()) {
	    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
	}
	?>
	<?php if ($enableRegister && $enableForceLogin): ?>
	<?php elseif ($enable && $enableShortCut && !$block->isLoggedIn()): ?>
		<li class="bss-b2b-customer">
			<a href="<?php echo $b2bCreateUrl; ?>">
				<?php echo $shortCutLinkText; ?>
			</a>
		</li>
	<?php endif; ?>

	<li class="authorization-link" 
		data-label="<?php 
		if ($enableRegister && $enableForceLogin): 

		else:
			echo $block->escapeHtml(__('or'));
		endif;
		?>">
	    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified */ echo $dataPostParam; ?>>
	        <?php echo $block->escapeHtml($block->getLabel()); ?>
	    </a>
	</li>
<?php else : ?>
	<?php
	if ($block->isLoggedIn()) {
	    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
	}
	?>
	<?php if ($enable && $enableShortCut && !$block->isLoggedIn()): ?>
		<li class="bss-b2b-customer">
			<a href="<?php echo $b2bCreateUrl; ?>">
				<?php echo $shortCutLinkText; ?>
			</a>
		</li>
	<?php endif; ?>
	<li class="authorization-link" data-label="<?php echo __('or'); ?>">
	    <a <?php /* @noEscape */ echo $block->getLinkAttributes(); ?><?php /* @noEscape */ echo $dataPostParam; ?>>
	        <?php echo $block->escapeHtml($block->getLabel()); ?>
	    </a>
	</li>
<?php endif; ?>

