<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Catalog\Block\Product\AbstractProduct $block */
/** @var \Aheadworks\Ctq\ViewModel\QuoteList\AddButton $viewModel */
$viewModel = $block->getQuoteListViewModel();
$product = $block->getProduct();
$buttonTitle = __('Add to Quote');
?>
<?php if ($product && $product->isSaleable() && $viewModel && $viewModel->isAllowedToAdd()): ?>
    <button type="button"
            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
            class="action primary toquotelist"
            id="product_addtoquotelist_button"
            data-mage-init='{"awCtqAddToQuoteListButton": {"isProductPage": true}}'
            disabled>
        <span><?= $block->escapeHtml($buttonTitle) ?></span>
    </button>
<?php endif; ?>