<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_BillPay
 * @codingStandardsIgnoreFile
 */
?>
<div class="admin__page-section-item order-account-information">
    <div class="admin__page-section-item-title">
        <span class="title">Payment Information</span>
    </div>
    <div class="admin__page-section-item-content">
        <?php $_payments = $block->getPayments(); ?>
        <?php if ($_payments && !empty($_payments)): ?>
            <table class="admin__table-secondary order-account-information-table">
                <tbody>
                    <tr>
                        <th>Cash Receipt Number</th>
                        <td><?php echo $block->escapeHtml($_payments['cash_receipt_number']); ?></td>
                    </tr>
                    <tr>
                        <th>Sync Status</th>
                        <td>
                            <?php if ($_payments['target_sync_status']):
                                    echo $block->escapeHtml(__("Synced"));
                                else:
                                    echo $block->escapeHtml(__('Payment Sync In  Process'));
                                endif;
                                ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Comments</th>
                        <td><?php echo $block->escapeHtml($_payments['payment_comment']); ?></td>
                    </tr>
                </tbody>
            </table>
        <?php else: ?>
            <div class="message info empty">
                <span><?php echo $block->escapeHtml(__('You have no transaction.')); ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
