
<div id="category-view-id"></div><?php
// @codingStandardsIgnoreFile
/** @var Magento\Catalog\Block\Product\ProductList\Item\Block $block */
$productId = $block->getProduct()->getId();
$productSku       = $block->getProduct()->getSku();
if ($productId):
?>
    <div class="vue-ai-product" id="vue-ai-product-<?= $productId ?>" data-vue="<?= $productId ?>"></div>
    <div class="vue-ai-sku" id="vue-ai-sku-<?= $productSku ?>" data-vue="<?= $productSku ?>">
<?php
endif;
?>

