<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Bss\CustomerAttributes\Block\Frontend\Order\Info */ ?>
<?php $data = $block->getCustomer();
/** @var  $customAttributes */
try {
    $customAttributes = $block->resultHelper()->getAttributesHtml($data->getId(), $block->getOrder());
} catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
} catch (\Magento\Framework\Exception\LocalizedException $e) {
}
?>
<?php if ($customAttributes) : ?>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?= /* @escapeNotVerified */ __('Customer Attributes Information') ?></strong>
        </div>
        <div class="block-content">
            <?php echo $customAttributes;  ?>
        </div>
    </div>
<?php endif; ?>

